---
title: "Informations about most popular stock codes and most loyal customers"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
df <- read_excel(here::here("online_retail_II.xlsx"))
library(dplyr)
library(stringr)
df <- df %>%
  filter(str_length(StockCode) == 5 |
           str_detect(StockCode, "^\\d{5}[a-zA-Z]{1,2}$") |
           str_detect(StockCode, "PADS|DCGS|SP|gift")) %>%
  filter(Price != 0) %>%
  mutate(CustomerID = as.character(`Customer ID`),
         Country = na_if(Country, "Unspecified"), .keep = "unused", .after = Price)
```

## Row 

### Most Popular Items {data-width=500}

```{r}
knitr:::kable(df %>%
                count(StockCode, Description, sort = TRUE, name = "Number of Occurrences") %>%
                left_join(df %>%
                            group_by(StockCode, Description) %>%
                            summarise("Median Price" = median(Price), .groups = "drop"), by = c("StockCode", "Description")) %>%
                relocate(`Median Price`, .after = "Description"))
```

### Inexpensive Items are More Frequently Sold {data-width=500}

```{r, fig.width=13}
library(ggplot2)
df %>%
  group_by(StockCode, Description) %>%
  mutate("Median Price" = median(Price)) %>%
  group_by("Price Bins" = cut(`Median Price`, 10), .drop = FALSE) %>%
  summarise("Number of Purchases" = n() + 1) %>%
#we add 1 to next use a logarithmic scale on the y axis  
  ggplot(aes(`Price Bins`, `Number of Purchases`, fill = `Price Bins`)) +
  geom_col(show.legend = FALSE)  +
  scale_fill_manual(values = c("#d55e00", rep("#999999", 9))) +
  scale_y_log10(labels = scales::label_number()) +
  geom_text(aes(label = `Number of Purchases` -1), vjust = -0.5) +
  labs(x = NULL,
       y = NULL,
       title = "Number of Purchases for Price Bin, Logarithmic Scale") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 22))
```

## Row

### Most Frequent Buyers {data-width=400}

```{r}
df_Customers <- df %>%
  filter(!is.na(CustomerID))
knitr:::kable(df_Customers %>%
                filter(!str_starts(Invoice, "C")) %>%
                mutate(Expense = Quantity * Price) %>%
                group_by(CustomerID) %>%
                summarise("Number of Invoices" = n_distinct(Invoice),
                          "Total of Expenses" = round(sum(Expense), 2)) %>%
                arrange(desc(`Total of Expenses`)) %>%
                left_join(df_Customers %>%
                            filter(!str_starts(Invoice, "C")) %>%
                            mutate(Month = format(InvoiceDate, "%y/%m")) %>%
                            group_by(CustomerID, Month) %>%
                            summarise("Number of Invoices" = n_distinct(Invoice), .groups = "drop") %>%
                            tidyr::pivot_wider(names_from = Month, values_from = `Number of Invoices`, names_sort = TRUE) %>%
                            mutate("Number of Missing Months" = rowSums(is.na(pick(everything())))), by = "CustomerID") %>%
                select(1, last_col(), 2, 3) %>%
                arrange(`Number of Missing Months`, desc(`Total of Expenses`)))
```

### Unfrequent Buyers still Contribute to the Total Revenues {data-width=600}

```{r, fig.width=15}
# df_Customers %>%
#   filter(!str_starts(Invoice, "C")) %>%
#   mutate(Expense = Quantity * Price) %>%
#   group_by(CustomerID) %>%
#   summarise("Number of Invoices" = n_distinct(Invoice),
#             "Total of Expenses" = round(sum(Expense), 2)) %>%
#   slice_max(`Total of Expenses`, n= 10) %>%
#   ggplot(aes(reorder(CustomerID, `Total of Expenses`), `Number of Invoices`)) +
#   geom_col()
# df_Customers %>%
#   filter(!str_starts(Invoice, "C")) %>%
#   mutate(Expense = Quantity * Price) %>%
#   group_by(CustomerID) %>%
#   summarise("Number of Invoices" = n_distinct(Invoice),
#             "Total of Expenses" = round(sum(Expense), 2)) %>%
#   mutate(Perc =`Total of Expenses` / sum(`Total of Expenses`))
# df_Customers %>%
#   filter(!str_starts(Invoice, "C")) %>%
#   mutate(Expense = Quantity * Price) %>%
#   group_by(CustomerID) %>%
#   summarise("Number of Invoices" = n_distinct(Invoice),
#             "Total of Expenses" = round(sum(Expense), 2)) %>%
#   ggplot(aes(`Total of Expenses`)) +
#   stat_ecdf()
# knitr:::kable(df_Customers %>%
#                 filter(!str_starts(Invoice, "C")) %>%
#                 mutate(Month = format(InvoiceDate, "%y/%m")) %>%
#                 group_by(CustomerID, Month) %>%
#                 summarise("Number of Invoices" = n_distinct(Invoice), .groups = "drop") %>%
#                 tidyr::pivot_wider(names_from = Month, values_from = `Number of Invoices`, names_sort = TRUE)  %>%
#                 mutate("Number of Invoices" = rowSums(across(where(is.numeric)), na.rm = TRUE),
#                        "Rounded Monthly Average" = round(rowMeans(across(where(is.numeric)), na.rm = TRUE), 2),
#                        "Number of Missing Months" = rowSums(is.na(pick(everything()))), .after = "CustomerID") %>%
#                 select(1:4) %>%
#                 filter(`Number of Missing Months` == 0) %>%
#                 arrange(desc(`Number of Invoices`)))
df_Customers %>%
  filter(!str_starts(Invoice, "C")) %>%
  mutate(Expense = Quantity * Price) %>%
  group_by(CustomerID) %>%
  summarise("Number of Invoices" = n_distinct(Invoice),
            "Total of Expenses" = round(sum(Expense), 2)) %>%
  arrange(desc(`Total of Expenses`)) %>%
  left_join(df_Customers %>%
              filter(!str_starts(Invoice, "C")) %>%
              mutate(Month = format(InvoiceDate, "%y/%m")) %>%
              group_by(CustomerID, Month) %>%
              summarise("Number of Invoices" = n_distinct(Invoice), .groups = "drop") %>%
              tidyr::pivot_wider(names_from = Month, values_from = `Number of Invoices`, names_sort = TRUE) %>%
              mutate("Number of Missing Months" = rowSums(is.na(pick(everything())))), by = "CustomerID") %>%
  group_by(`Number of Missing Months`) %>%
  summarise("Total Rounded Revenues" = round(sum(`Total of Expenses`))) %>%
  ggplot(aes(`Number of Missing Months`, `Total Rounded Revenues`, fill = forcats::fct_rev(ifelse(`Total Rounded Revenues` > sum(`Total Rounded Revenues`) / 13, "More than 1/13th over the Total", "Less or Equal to 1/13th over the Total")))) +
  geom_col() +
  scale_fill_manual(values = c("#f0e442", "#999999", 9)) +
  geom_text(aes(label = `Total Rounded Revenues`), vjust = -0.5) +
  labs(x = NULL,
       y = NULL,
       title = "Total Rounded Revenues per Bracket of Missing Months") +
  theme(axis.text.y = element_blank(),
        text = element_text(size = 22),
        legend.position = "bottom", 
        legend.title = element_blank())
```